# Импортируйте тему
theme: jekyll-theme-chirpy
# Язык веб-страницы ' http://www.lingoes.net/en/translator/langcode.htm
# Если он совпадает с именем одного из файлов в папке `_data/locales`, язык макета также будет изменен,
# в противном случае язык макета будет использовать значение по умолчанию 'en'.
lang: ru-RU

# Переключитесь на свой часовой пояс › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Moscow

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Олег Казанин # the main title
tagline: Добро пожаловать в мой блог! Здесь я делюсь своими знаниями и опытом в сфере ИТ-технологий, разбираю свои проекты, решаю проблемы. Спасибо за ваш визит! # it will display as the sub-title
description: Добро пожаловать в мой блог! Здесь я делюсь своими знаниями и опытом в сфере ИТ-технологий, разбираю свои проекты, решаю проблемы. Спасибо за ваш визит!
author: Олег Казанин
# Введите протокол и имя хоста для вашего сайта.
# например, 'https://username.github.io', обратите внимание, что оно не заканчивается на '/'.
url: ""

github:
  username: olegsanych # change to your github username
vk:
  username: olegsanychmsk
telegram:
  username: hardcode_msk

social:
  # Измените на свое полное имя.
  # Оно будет отображаться в качестве автора по умолчанию и владельца авторских прав в нижнем колонтитуле
  name: Олег Казанин
  email: oakazanin@ya.ru # change to your email address
  links:
    # Первый элемент служит ссылкой на владельца авторских прав
    - https://vk.com/olegsanychmsk
    - https://github.com/olegsanych
    - https://t.me/hardcode_msk

# Настройки проверки сайта
webmaster_verifications:
  google: # введите проверочный код Google
  yandex: # Введите проверочный код Яндекса

# ↑ --------------------------
# Конец настроек `jekyll-seo-tag`.

# Настройки веб-аналитики
analytics:
  google:
    id: # fill in your Google Analytics ID
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token

# Параметры просмотра страниц
pageviews:
  provider: # теперь поддерживается только 'goatcounter'

# Предпочтительная настройка цветовой схемы.
theme_mode: # [light | dark]

# Конечная точка CDN для медиаресурсов.
# Обратите внимание, что после присвоения этого адреса CDN url
# будет добавлен ко всем медиаресурсам (аватар сайта, изображения постов, аудио- и видеофайлы), путь к которым начинается с '/'.
#
# e.g. 'https://cdn.com'
cdn:

# аватар на боковой панели, поддержка локальных или CORS-ресурсов
avatar: assets/img/avatar_bw.webp

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# # тип boolean, вкл / выкл оглавление в постах.
toc: true

comments:
  # Вкл / Выкл систему комментариев к постам. Если оставить его пустым, он будет отключен.
  provider: # [disqus | utterances | giscus]
  # Варианты поставщиков:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ Не рекомендуется изменять следующие параметры ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # Пустая строка здесь означает, что все файлы в проекте
      type: posts
    values:
      layout: post
      comments: true # Включите комментарии в постах.
      toc: true # Отображение колонки оглавления в постах.
      # НЕ изменяйте следующий параметр, если вы не уверены, 
      # что сможете обновить все ссылки на посты.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# ------------ Мои настройки ------------------
plugins:
  - jekyll-seo-tag

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
      published: false
      sitemap: false


permalink: /:categories/:title/ # Переопределяю формат URL

# не публиковать посты сразу, время которых ПОЗДНЕЕ времени публикации
future: false